/******************************************************************************
 * measure_inference.c — drop-in replacement for the main loop generated by
 * `ai8xize.py` for any of the five CIFAR-10 variants. Runs N inferences in a
 * tight loop, reports per-inference CNN cycles + end-to-end wall time, and
 * toggles a GPIO around each CNN call so an external power monitor can sync.
 *
 * Usage: copy this file as main.c into the synthesized project directory,
 * then build and flash normally.  See max78000-implementation/c_harness/README.md.
 *
 * Set MACS_PER_INFERENCE to the correct value for your variant:
 * baseline:     4433920   improved:    4433920
 * mininet:     23004416   deeper:      7963904   wide_improved: 9305088
 * Override at build time:  make CFLAGS_EXTRA="-DMACS_PER_INFERENCE=4433920"
 *
 * Pin assignment for the energy trigger:
 * EVKIT_V1:  P0.6  (J5-7, free)
 * FTHR_RevA: P2.0  (header pin "MISO" on the Feather header)
 *
 * Build with: `make BOARD=FTHR_RevA -j`
 *****************************************************************************/

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "mxc.h"
#include "mxc_delay.h"
#include "mxc_device.h"
#include "board.h"
#include "gpio.h"
#include "led.h"
#include "uart.h"

/* Generated by ai8xize.py — DO NOT modify these from this file. */
#include "cnn.h"
#include "sampledata.h"      /* one CIFAR-10 image, int8-quantized */

/* Number of class labels — keep in sync with cnn.h::CNN_NUM_OUTPUTS. */
#define NUM_CLASSES 10

/* MACs per inference — override per variant at build time */
#ifndef MACS_PER_INFERENCE
#  define MACS_PER_INFERENCE  4433920UL   /* baseline default */
#endif

/* How many inferences to time. */
#define N_INFERENCES 1000

/* GPIO pin asserted while the CNN is running. */
#ifdef BOARD_EVKIT_V1
  #define MEASURE_GPIO_PORT MXC_GPIO0
  #define MEASURE_GPIO_PIN  MXC_GPIO_PIN_6
#else  /* FTHR */
  #define MEASURE_GPIO_PORT MXC_GPIO2
  #define MEASURE_GPIO_PIN  MXC_GPIO_PIN_0
#endif

/* cnn_time és heretat com a extern des de cnn.c */
volatile uint32_t cnn_time;

void load_input(void);

/* ---- helpers ------------------------------------------------------------- */

static void measure_pin_init(void)
{
    mxc_gpio_cfg_t cfg = {
        .port = MEASURE_GPIO_PORT,
        .mask = MEASURE_GPIO_PIN,
        .pad = MXC_GPIO_PAD_NONE,
        .func = MXC_GPIO_FUNC_OUT,
        .vssel = MXC_GPIO_VSSEL_VDDIOH,
    };
    MXC_GPIO_Config(&cfg);
    MXC_GPIO_OutClr(cfg.port, cfg.mask);
}

static inline void measure_pin_high(void)
{ MXC_GPIO_OutSet(MEASURE_GPIO_PORT, MEASURE_GPIO_PIN); }

static inline void measure_pin_low(void)
{ MXC_GPIO_OutClr(MEASURE_GPIO_PORT, MEASURE_GPIO_PIN); }

static void sort_u32(uint32_t *a, int n)
{
    for (int i = 1; i < n; i++) {
        uint32_t key = a[i];
        int j = i - 1;
        while (j >= 0 && a[j] > key) { a[j+1] = a[j]; j--; }
        a[j+1] = key;
    }
}

static int classify(int32_t *ml_data, int *out_argmax)
{
    int32_t best = ml_data[0];
    int idx = 0;
    for (int i = 1; i < NUM_CLASSES; i++) {
        if (ml_data[i] > best) { best = ml_data[i]; idx = i; }
    }
    *out_argmax = idx;
    return (int)best;
}

/* ---- main ---------------------------------------------------------------- */

int main(void)
{
    /* Bring the core up at 100 MHz from the internal oscillator. */
    MXC_ICC_Enable(MXC_ICC0);
    MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
    SystemCoreClockUpdate();

    /* UART for printf — 115200 8N1 on the board's USB CDC ACM. */
    Console_Init();

    printf("\n*** MAX78000 CIFAR-10 — measurement harness ***\n");
    printf("System clock: %lu Hz\n", SystemCoreClock);

    /* GPIO for power-monitor sync. */
    measure_pin_init();

    /* Bring up the CNN accelerator. */
    if (cnn_init() != CNN_OK) {
        printf("ERROR: cnn_init failed\n"); while (1) {}
    }
    cnn_load_weights();
    cnn_load_bias();
    cnn_configure();

    int32_t ml_data[NUM_CLASSES];

    /* Per-inference cycle counts and wall times. */
    uint32_t cnn_cycles[N_INFERENCES];
    uint32_t wall_us[N_INFERENCES];

    /* Configurem el SysTick com a comptador de temps global infal·lible */
    SysTick->LOAD = 0x00FFFFFFUL; 
    SysTick->CTRL = SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk;

    /* Pre-load the sample image once. */
    load_input();   

    int last_class = -1;
    int32_t last_score = 0;

    printf("Running %d inferences...\n", N_INFERENCES);
    for (int i = 0; i < N_INFERENCES; i++) {
        cnn_time = 0;
        
        // Reset del comptador de cicles SysTick i captura inicial
        SysTick->VAL = 0;
        uint32_t t_start = SysTick->VAL;
        
        measure_pin_high();
        cnn_start();
        
        /* MODIFICACIÓ CLAU: Espera activa segura amb barrera de memòria */
        while (cnn_time == 0) { 
            __asm volatile("" : : : "memory"); 
        }

        measure_pin_low();
        uint32_t t_end = SysTick->VAL;

        cnn_unload((uint32_t *)ml_data);
        classify(ml_data, &last_class);
        last_score = ml_data[last_class];

        // Capturem els cicles interns de l'accelerador reportats per la ISR
        cnn_cycles[i] = cnn_time;
        
        // Calculem la latència real de rellotge (SysTick és un down-counter)
        uint32_t elapsed_cycles = 0;
        if (t_start >= t_end) {
            elapsed_cycles = t_start - t_end;
        } else {
            elapsed_cycles = (0x00FFFFFFUL - t_end) + t_start;
        }

        // A 100 MHz, Cicles / 100 = Microsegons (us)
        wall_us[i] = elapsed_cycles / (SystemCoreClock / 1000000U);
    }

    /* Desactivem el SysTick un cop acabat el loop */
    SysTick->CTRL = 0;

    /* Reporting ---------------------------------------------------------- */

    sort_u32(cnn_cycles, N_INFERENCES);
    sort_u32(wall_us, N_INFERENCES);

    uint32_t cnn_median = cnn_cycles[N_INFERENCES / 2];
    uint32_t cnn_min    = cnn_cycles[0];
    uint32_t cnn_max    = cnn_cycles[N_INFERENCES - 1];
    uint32_t wall_median = wall_us[N_INFERENCES / 2];
    uint32_t wall_min    = wall_us[0];
    uint32_t wall_max    = wall_us[N_INFERENCES - 1];

    // Càlcul del temps de la CNN basat en la freqüència real de l'accelerador
    float cnn_us = (float)cnn_median / (CNN_CLOCK_FREQ_HZ / 1e6f);

    printf("\n----- Results (N=%d) -----\n", N_INFERENCES);
    printf("Last classification : class %d (logit %ld)\n", last_class, (long)last_score);
    printf("\nCNN-only cycles (accelerator):\n");
    printf("  median = %lu   (~%.1f us @ %.1f MHz)\n",
           (unsigned long)cnn_median, cnn_us, CNN_CLOCK_FREQ_HZ / 1e6f);
    printf("  min    = %lu\n", (unsigned long)cnn_min);
    printf("  max    = %lu\n", (unsigned long)cnn_max);

    printf("\nEnd-to-end latency (CNN + M4 overhead):\n");
    printf("  median = %lu us\n", (unsigned long)wall_median);
    printf("  min    = %lu us\n", (unsigned long)wall_min);
    printf("  max    = %lu us\n", (unsigned long)wall_max);

    /* Throughput calculat basant-se en les operacions realitzades */
    float mops_per_sec = 2.0f * MACS_PER_INFERENCE / (cnn_us * 1e-6f) / 1e6f;
    printf("\nThroughput: %.1f MOPS/sec  (assuming MACs/inf = %lu)\n",
           mops_per_sec, (unsigned long)MACS_PER_INFERENCE);

    printf("\nFor energy/inference:\n");
    printf("  Sync your power monitor's trigger to the GPIO P%d.%d\n",
           (int)(MEASURE_GPIO_PORT == MXC_GPIO0 ? 0 : 2),
           __builtin_ctz(MEASURE_GPIO_PIN));
    printf("  Energy = integral of V*I over the time the pin is HIGH.\n");

    /* Idle blink so we can tell the run finished. */
    cnn_disable();
    while (1) {
        LED_On(LED1); MXC_Delay(MXC_DELAY_MSEC(250));
        LED_Off(LED1); MXC_Delay(MXC_DELAY_MSEC(250));
    }
    return 0;
}